package uk.ac.ebi.eva.submission.model.metadata;

public enum ExperimentType {
    WHOLE_GENOME_SEQUENCING, WHOLE_TRANSCRIPTOME_SEQUENCING, EXOME_SEQUENCING, GENOTYPING_BY_ARRAY,
    CURATION, GENOTYPING_BY_SEQUENCING, TARGET_SEQUENCING, TRANSCRIPTOMICS
}
